name: Check for new Grpc release

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  check-release:
    runs-on: ubuntu-20.04
    
    outputs:
      latest-release: ${{ steps.latest.outputs.LATEST_RELEASE }}
      current-release: ${{ steps.current.outputs.CURRENT_RELEASE }}

    steps:
      - uses: actions/checkout@v2
          
  build-new-release:
    needs: [check-release]
    uses: ./.github/workflows/build_grpc.yaml
    with:
      release: ${{ needs.check-release.outputs.latest-release }}
