name: Check for new jq release

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  check-release:
    runs-on: ubuntu-20.04
    
    outputs:
      latest-release: ${{ steps.latest.outputs.LATEST_RELEASE }}

    steps:
      - uses: actions/checkout@v2
      
      - name: Get latest jq release
        id: latest
        run: |
          
          GE_LATEST=1.6
          echo '::set-output name=LATEST_RELEASE::'$GE_LATEST
          echo "Latest JQ version: "$GE_LATEST
          echo "Latest JQ version: "${{ needs.check-release.outputs.latest-release }}
  build-new-release:
    uses: ./.github/workflows/build_jq.yaml
    with:
      release: ${{ needs.check-release.outputs.latest-release }}
